"""Annual metrics (Excel: Annual_Metrics)."""
from tortoise import fields
from tortoise.models import Model


class AnnualMetrics(Model):
    id = fields.IntField(pk=True)
    scrip_code = fields.CharField(max_length=32, index=True)
    period = fields.CharField(max_length=64, index=True)
    category = fields.CharField(max_length=16, index=True)  # std | con
    p_l_json = fields.TextField(null=True)
    balance_sheet_json = fields.TextField(null=True)
    cash_flow_json = fields.TextField(null=True)
    ratios_json = fields.TextField(null=True)
    currency = fields.CharField(max_length=16, null=True)
    level_of_rounding = fields.CharField(max_length=64, null=True)

    sales = fields.FloatField(null=True)
    exceptional_items = fields.FloatField(null=True)
    other_income_normal = fields.FloatField(null=True)
    interest = fields.FloatField(null=True)
    depreciation = fields.FloatField(null=True)
    profit_before_tax = fields.FloatField(null=True)
    profit_after_tax = fields.FloatField(null=True)
    tax = fields.FloatField(null=True)
    eps_in_rs = fields.FloatField(null=True)
    net_profit = fields.FloatField(null=True)
    other_income = fields.FloatField(null=True)
    expenses = fields.FloatField(null=True)
    operating_profit = fields.FloatField(null=True)
    ebitda = fields.FloatField(null=True)
    revenue_growth_percent = fields.FloatField(null=True)
    ebitda_margin_percent = fields.FloatField(null=True)
    ebit = fields.FloatField(null=True)
    opm_percent = fields.FloatField(null=True)
    tax_percent = fields.FloatField(null=True)
    net_profit_margin = fields.FloatField(null=True)
    dividend_paid = fields.FloatField(null=True)
    dividend_payout_percent = fields.FloatField(null=True)
    equity_capital = fields.FloatField(null=True)
    reserves = fields.FloatField(null=True)
    total_liabilities = fields.FloatField(null=True)
    current_ratio = fields.FloatField(null=True)
    quick_ratio = fields.FloatField(null=True)
    total_equity = fields.FloatField(null=True)
    total_assets = fields.FloatField(null=True)
    debt_to_equity = fields.FloatField(null=True)
    working_capital = fields.FloatField(null=True)
    cwip = fields.FloatField(null=True)
    investments = fields.FloatField(null=True)
    borrowings = fields.FloatField(null=True)
    debt_to_assets = fields.FloatField(null=True)
    cash_from_operating_activity = fields.FloatField(null=True)
    cash_from_investing_activity = fields.FloatField(null=True)
    dividends_received = fields.FloatField(null=True)
    cash_from_financing_activity = fields.FloatField(null=True)
    cash_conversion_ratio = fields.FloatField(null=True)
    net_cash_flow = fields.FloatField(null=True)
    cfo_op = fields.FloatField(null=True)
    roa = fields.FloatField(null=True)
    roe = fields.FloatField(null=True)
    roce_percent = fields.FloatField(null=True)
    debtor_days = fields.FloatField(null=True)
    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "Annual_Metrics"
        unique_together = (("scrip_code", "period", "category"),)
