from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable, Any


@dataclass(frozen=True)
class PortalLocators:
    search_input: str
    suggestion_items: str
    result_period_dropdown: str
    industry_dropdown: str
    broadcast_dropdown: str
    submit_button: str
    results_grid: str


@runtime_checkable
class ResultsPortalContract(Protocol):
    TARGET_URL: str
    HOME_URL: str

    async def prepare_page(self, ctx: Any) -> Any: ...
    async def navigate(self, page: Any) -> None: ...
    async def fill_search(self, page: Any, company: str) -> None: ...
    async def apply_filters(self, page: Any) -> None: ...
    async def submit(self, page: Any) -> None: ...
    async def wait_results(self, page: Any) -> None: ...
    async def results_container(self, page: Any) -> Any: ...
    async def data_rows(self, grid: Any) -> Any: ...
    async def document_anchors(self, scope: Any) -> Any: ...
    async def resolve_absolute_url(self, page: Any, href: str) -> str: ...
